version: '3'
services:
    api-service:
        build: ./api/
        volumes: 
            - ./api/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    nginx:
        build: ./nginx/
        ports:
          - 80:80
