apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: cr.yandex/crpurmch681deghm39te/api:v2.3
        name: api
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "10.129.0.38"
        - name: STORAGE_TYPE
          value: "db"
